"""device_tokens, notification_state 테이블 추가 (실제 푸시 발송)

Revision ID: 08c5f2f24c83
Revises: 6adb524be5ad
Create Date: 2026-08-25 04:23:18.214596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c5f2f24c83'
down_revision: Union[str, Sequence[str], None] = '6adb524be5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_internal_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_tokens_user_internal_id'), ['user_internal_id'], unique=False)

    op.create_table('notification_state',
    sa.Column('user_internal_id', sa.Integer(), nullable=False),
    sa.Column('alert_active', sa.Boolean(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('user_internal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_state')
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_tokens_user_internal_id'))
        batch_op.drop_index(batch_op.f('ix_device_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_device_tokens_id'))

    op.drop_table('device_tokens')
    # ### end Alembic commands ###
