"""donation_records에 donation_method_code 추가

Revision ID: 6adb524be5ad
Revises: d421e86f906c
Create Date: 2026-08-25 03:18:43.368048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6adb524be5ad'
down_revision: Union[str, Sequence[str], None] = 'd421e86f906c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # autogenerate가 처음부터 NOT NULL로 만들어주는데, 이미 데이터가 있는 테이블에
    # 기본값 없이 NOT NULL 컬럼을 추가하면 실패한다. 그래서 손으로 세 단계로 나눴다:
    # 1) nullable로 컬럼 추가  2) 기존 행을 donation_method 값으로 역산해서 채움
    # 3) 다 채워진 뒤에 NOT NULL로 잠금.
    # 여기 쓴 판정 로직은 app/services/donation_method.py의 resolve_donation_method_code()를
    # 그대로 옮긴 것이다 - 마이그레이션은 나중에 그 함수가 바뀌어도 그때 기준으로 다시
    # 실행되면 안 되므로(과거 시점 스냅샷이어야 함) app 코드를 import하지 않고 그대로 적었다.
    with op.batch_alter_table('donation_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donation_method_code', sa.String(), nullable=True))

    conn = op.get_bind()
    conn.execute(sa.text(
        "UPDATE donation_records SET donation_method_code = 'WHOLE_BLOOD' "
        "WHERE donation_method LIKE '%전혈%'"
    ))
    conn.execute(sa.text(
        "UPDATE donation_records SET donation_method_code = 'PLATELET_PLASMA' "
        "WHERE donation_method_code IS NULL "
        "AND donation_method LIKE '%혈소판%' AND donation_method LIKE '%혈장%'"
    ))
    conn.execute(sa.text(
        "UPDATE donation_records SET donation_method_code = 'PLATELET' "
        "WHERE donation_method_code IS NULL AND donation_method LIKE '%혈소판%'"
    ))
    conn.execute(sa.text(
        "UPDATE donation_records SET donation_method_code = 'PLASMA' "
        "WHERE donation_method_code IS NULL AND donation_method LIKE '%혈장%'"
    ))

    remaining = conn.execute(sa.text(
        "SELECT COUNT(*) FROM donation_records WHERE donation_method_code IS NULL"
    )).scalar()
    if remaining:
        raise RuntimeError(
            f"donation_method_code로 역산이 안 되는 donation_records가 {remaining}건 있습니다. "
            "이 마이그레이션을 적용하기 전에 해당 행들의 donation_method 값을 먼저 확인하세요."
        )

    with op.batch_alter_table('donation_records', schema=None) as batch_op:
        batch_op.alter_column('donation_method_code', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation_records', schema=None) as batch_op:
        batch_op.drop_column('donation_method_code')

    # ### end Alembic commands ###
